name: Test & Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test on all supported devices
        id: run_tests
        uses: adamjakab/action-connectiq-builder@v1
        with:
          verbose: 1
          operation: TEST
          devices: fr235,vivoactive,vivoactive4
          certificate: ${{ secrets.CONNECTIQ_DEVELOPER_KEY_BASE64}}
  release:
    needs: test
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Package App
        id: package_app
        uses: adamjakab/action-connectiq-builder@v1
        with:
          verbose: 1
          operation: PACKAGE
          certificate: ${{ secrets.CONNECTIQ_DEVELOPER_KEY_BASE64}}
          package_name: aApp_${{ github.ref_name }}.iq
      - name: Check Package Path
        run: |
          echo "Relative Package Path: '${{ steps.package_app.outputs.package_path }}'"
          echo "Absolute Package Path: '${{ github.workspace }}/${{ steps.package_app.outputs.package_path }}'"
          ls -la "${{ github.workspace }}/${{ steps.package_app.outputs.package_path }}"
      - name: Create New Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: ${{ github.workspace }}/${{ steps.package_app.outputs.package_path }}
